version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: dirhtml
  configuration: docs/conf.py

formats:
  - pdf
  - epub
