.\" Manpage for mopidyctl
.TH "MOPIDYCTL" "8" "October 11, 2014" "1.0" "mopidyctl"
.SH NAME
mopidyctl \- manage the Mopidy music server system service
.SH SYNOPSIS
.B mopidyctl
[any mopidy(1) option]
.SH DESCRIPTION
The \fBmopidyctl\fP command runs \fBmopidy\fP subcommands in the
same environment as the Mopidy system service is running in. That is, as the
same user and with the same config as the Mopidy system service is using.
.SH OPTIONS
mopidyctl(8) takes the same options as mopidy(1).
.SH SEE ALSO
mopidy(1)
.SH COPYRIGHT
2014, Stein Magnus Jodal and contributors
