name: "Ubuntu devel"

on:
  schedule:
    # Every Friday at 18:20 UTC, so we can fix the issue over the weekend
    - cron: "20 18 * * 5"
  workflow_dispatch:

jobs:
  main:
    name: "Test: Python 3.14"
    runs-on: ubuntu-24.04

    # The container should be automatically updated from time to time.
    container: ubuntu:devel

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-ugly \
            libcairo2-dev \
            libgirepository-2.0-dev \
            libglib2.0-dev \
            python3 \
            python3-gst-1.0 \
            tox
      - uses: actions/checkout@v6
      - run: tox -e py314
